[repository]
name = "form-block"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/plone/form-block-"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "plone.formblock"
path = "backend"
code_path = "src/plone/formblock"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@plone/volto-form-block"
path = "frontend/packages/volto-form-block"
code_path = "src"
changelog = "frontend/packages/volto-form-block/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-form-block/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "6678734cc3713f3fab9ea510616cef59dc466514"
generated_date = "2026-06-10 21:46:19"
